export default function generate(
    avatar: string,
    name: string,
    role: string,
    email: string,
    additionalContact: string,
    color: "dark" | "light" = "light"
): string {
    if (avatar.length > 0) {
        return `<div><div style="word-break:break-word;box-sizing:border-box;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-flex-wrap:nowrap;-webkit-flex-wrap:nowrap;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:start;-ms-flex-pack:start;-webkit-justify-content:flex-start;justify-content:flex-start;gap:16px;"><div style="-webkit-tap-highlight-color:transparent;box-sizing:border-box;position:relative;display:block;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;overflow:hidden;width:94px;min-width:94px;height:94px;border-radius:8px;-webkit-text-decoration:none;text-decoration:none;border:0;background-color:transparent;padding:0;"><img style="object-fit:cover;width:100%;height:100%;display:block;"src="${escape(
            avatar
        )}"alt="${escape(
            name
        )}'s Avatar"/></div><div><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:#909296;font-size:12px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;font-weight:700;text-transform:uppercase;">user</div><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:inherit;font-size:18px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;font-weight:500;font-family:GreycliffCF,-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;">${escape(
            name
        )}</div><div style="box-sizing:border-box;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-flex-wrap:nowrap;-webkit-flex-wrap:nowrap;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:start;-ms-flex-pack:start;-webkit-justify-content:flex-start;justify-content:flex-start;gap:10px;margin-top:3px;"><svgxmlns="http://www.w3.org/2000/svg"width="16"height="16"viewBox="0 0 24 24"stroke-width="1.5"stroke="currentColor"fill="none"stroke-linecap="round"stroke-linejoin="round"style="color:#5c5f66"><pathstroke="none"d="M0 0h24v24H0z"fill="none"></path><circlecx="12"cy="12"r="4"></circle><path d="M16 12v1.5a2.5 2.5 0 0 0 5 0v-1.5a9 9 0 1 0 -5.5 8.28"></path></svg><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:#909296;font-size:12px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;">${escape(
            email
        )}</div></div><div style="box-sizing:border-box;-webkit-box-flex:0;-webkit-flex-grow:0;-ms-flex-positive:0;flex-grow:0;font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:#909296;font-size:12px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;margin-top:5px;">${escape(
            additionalContact
        )}</div></div></div></div>`;
    } else if (name.toLowerCase() === name) {
        return `<div><div style="box-sizing:border-box;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-flex-wrap:nowrap;-webkit-flex-wrap:nowrap;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:start;-ms-flex-pack:start;-webkit-justify-content:flex-start;justify-content:flex-start;gap:16px;"><div style="-webkit-tap-highlight-color:transparent;box-sizing:border-box;position:relative;display:block;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;overflow:hidden;width:94px;min-width:94px;height:94px;border-radius:8px;-webkit-text-decoration:none;text-decoration:none;border:0;background-color:transparent;padding:0;-webkit-box-flex:0;flex-grow:0;"><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;font-size:37.6px;color:#e9ecef;font-weight:700;${
            color === "dark" ? "background-color: rgba(52,58,64,0.2)" : ""
        };display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-ms-flex-pack:center;-webkit-justify-content:center;justify-content:center;width:100%;height:100%;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;border:1pxsolidtransparent;border-radius:8px;"title="aaaaaaaaa's Avatar"><svg style="width:70%;height:70%;color:${
            color === "dark" ? "#e9ecef" : "#868e96"
        }"width="15"height="15"viewBox="0 0 15 15"fill="none"xmlns="http://www.w3.org/2000/svg"><path d="M0.877014 7.49988C0.877014 3.84219 3.84216 0.877045 7.49985 0.877045C11.1575 0.877045 14.1227 3.84219 14.1227 7.49988C14.1227 11.1575 11.1575 14.1227 7.49985 14.1227C3.84216 14.1227 0.877014 11.1575 0.877014 7.49988ZM7.49985 1.82704C4.36683 1.82704 1.82701 4.36686 1.82701 7.49988C1.82701 8.97196 2.38774 10.3131 3.30727 11.3213C4.19074 9.94119 5.73818 9.02499 7.50023 9.02499C9.26206 9.02499 10.8093 9.94097 11.6929 11.3208C12.6121 10.3127 13.1727 8.97172 13.1727 7.49988C13.1727 4.36686 10.6328 1.82704 7.49985 1.82704ZM10.9818 11.9787C10.2839 10.7795 8.9857 9.97499 7.50023 9.97499C6.01458 9.97499 4.71624 10.7797 4.01845 11.9791C4.97952 12.7272 6.18765 13.1727 7.49985 13.1727C8.81227 13.1727 10.0206 12.727 10.9818 11.9787ZM5.14999 6.50487C5.14999 5.207 6.20212 4.15487 7.49999 4.15487C8.79786 4.15487 9.84999 5.207 9.84999 6.50487C9.84999 7.80274 8.79786 8.85487 7.49999 8.85487C6.20212 8.85487 5.14999 7.80274 5.14999 6.50487ZM7.49999 5.10487C6.72679 5.10487 6.09999 5.73167 6.09999 6.50487C6.09999 7.27807 6.72679 7.90487 7.49999 7.90487C8.27319 7.90487 8.89999 7.27807 8.89999 6.50487C8.89999 5.73167 8.27319 5.10487 7.49999 5.10487Z"fill="currentColor"fill-rule="evenodd"clip-rule="evenodd"></path></svg></div></div><div><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:#909296;font-size:12px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;font-weight:700;text-transform:uppercase;">${escape(
            role
        )}</div><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:inherit;font-size:18px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;font-weight:500;font-family:GreycliffCF,-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;">${escape(
            name
        )}</div><div style="box-sizing:border-box;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-flex-wrap:nowrap;-webkit-flex-wrap:nowrap;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:start;-ms-flex-pack:start;-webkit-justify-content:flex-start;justify-content:flex-start;gap:10px;margin-top:3px;"><svgxmlns="http://www.w3.org/2000/svg"width="16"height="16"viewBox="0 0 24 24"stroke-width="1.5"stroke="currentColor"fill="none"stroke-linecap="round"stroke-linejoin="round"style="color:#5c5f66"><pathstroke="none"d="M0 0h24v24H0z"fill="none"></path><circlecx="12"cy="12"r="4"></circle><path d="M16 12v1.5a2.5 2.5 0 0 0 5 0v-1.5a9 9 0 1 0 -5.5 8.28"></path></svg><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:#909296;font-size:12px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;box-sizing:border-box;-webkit-box-flex:0;-webkit-flex-grow:0;-ms-flex-positive:0;flex-grow:0;">${escape(
            email
        )}</div></div><div style="box-sizing:border-box;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-flex-wrap:nowrap;-webkit-flex-wrap:nowrap;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:start;-ms-flex-pack:start;-webkit-justify-content:flex-start;justify-content:flex-start;gap:10px;margin-top:5px;"><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:#909296;font-size:12px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;box-sizing:border-box;-webkit-box-flex:0;-webkit-flex-grow:0;-ms-flex-positive:0;flex-grow:0;">${escape(
            additionalContact
        )}</div></div></div></div></div>`;
    }
    return `<div><div style="box-sizing:border-box;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-flex-wrap:nowrap;-webkit-flex-wrap:nowrap;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:start;-ms-flex-pack:start;-webkit-justify-content:flex-start;justify-content:flex-start;gap:16px;"><div style="-webkit-tap-highlight-color:transparent;box-sizing:border-box;position:relative;display:block;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;overflow:hidden;width:94px;min-width:94px;height:94px;border-radius:8px;-webkit-text-decoration:none;text-decoration:none;border:0;background-color:transparent;padding:0;"><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;font-size:37.6px;color:${color === "dark" ? "#e9ecef":"#868e96"};font-weight:700;background-color:${
        color === "dark" ? "rgba(52,58,64,0.2)" : "rgba(248,249,250,1)"
    };display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-ms-flex-pack:center;-webkit-justify-content:center;justify-content:center;width:100%;height:100%;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;border:1pxsolidtransparent;border-radius:8px;"title="${escape(
        name
    )}'s Avatar">${escape(
        name
            .split("")
            .map((el) => (el.match(/[A-Z]/) ? el : ""))
            .join("")
    )}</div></div><div><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:#909296;font-size:12px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;font-weight:700;text-transform:uppercase;">${escape(
        role
    )}</div><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:inherit;font-size:18px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;font-weight:500;font-family:GreycliffCF,-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;">${escape(
        name
    )}</div><div style="box-sizing:border-box;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-flex-wrap:nowrap;-webkit-flex-wrap:nowrap;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:start;-ms-flex-pack:start;-webkit-justify-content:flex-start;justify-content:flex-start;gap:10px;margin-top:3px;"><svgxmlns="http://www.w3.org/2000/svg"style="color:#5c5f66"width="16"height="16"viewBox="0 0 24 24"stroke-width="1.5"stroke="currentColor"fill="none"stroke-linecap="round"stroke-linejoin="round"><pathstroke="none"d="M0 0h24v24H0z"fill="none"></path><circlecx="12"cy="12"r="4"></circle><path d="M16 12v1.5a2.5 2.5 0 0 0 5 0v-1.5a9 9 0 1 0 -5.5 8.28"></path></svg><div style="font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:#909296;font-size:12px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;box-sizing:border-box;-webkit-box-flex:0;-webkit-flex-grow:0;-ms-flex-positive:0;flex-grow:0;">${escape(
        email
    )}</div></div><div style="box-sizing:border-box;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-flex-wrap:nowrap;-webkit-flex-wrap:nowrap;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:start;-ms-flex-pack:start;-webkit-justify-content:flex-start;justify-content:flex-start;gap:10px;margin-top:5px;"><div style="box-sizing:border-box;-webkit-box-flex:0;-webkit-flex-grow:0;-ms-flex-positive:0;flex-grow:0;font-family:-apple-system,BlinkMacSystemFont,SegoeUI,Roboto,Helvetica,Arial,sans-serif,AppleColorEmoji,SegoeUIEmoji;-webkit-tap-highlight-color:transparent;color:#909296;font-size:12px;line-height:1.55;-webkit-text-decoration:none;text-decoration:none;">${escape(
        additionalContact
    )}</div style=></div></div></div></div>`;
}
function escape(str: string): string {
    return str
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;");
}
